In [46]:
import numpy as np
import pandas as pd
import util

In [47]:
PATH_STATION_SCHEDULE = "../raw_data/selected/부산교통공사_부산도시철도 운행 정보.csv"
PATH_STATION_SCHEDULE_REFINE= "../trimmed_data/stationSchedule.json"

# `02-station-schedule-read.ipynb`
> `배차간역` : 한 역에서 어떤 열차가 지나가고 다음 열차가 올 때까지의 시간
- 한 역에서의 `배차간격` 데이터

## 1. 데이터 불러오기

In [48]:
# RawData
df = pd.read_csv(PATH_STATION_SCHEDULE,encoding="EUC-KR")
df.head(3)

,열차번호,노선번호,노선명,운행구간기점명,운행구간종점명,운행유형,요일구분,운행구간정거장,정거장도착시각,정거장출발시각,운행속도,운영기관전화번호,데이터기준일자
0,1001,S2601,부산 도시철도 1호선,노포,다대포해수욕장,일반,평일,001-노포+002-범어사+003-남산+004-두실+005-구서+006-장전+007...,001-05:08+002-05:09+003-05:11+004-05:13+005-05...,001-05:08+002-05:10+003-05:12+004-05:13+005-05...,39.6km/h,1544-5005,2023-07-11
1,1003,S2601,부산 도시철도 1호선,노포,다대포해수욕장,일반,평일,001-노포+002-범어사+003-남산+004-두실+005-구서+006-장전+007...,001-05:18+002-05:20+003-05:22+004-05:23+005-05...,001-05:18+002-05:20+003-05:22+004-05:24+005-05...,39.6km/h,1544-5005,2023-07-11
2,1005,S2601,부산 도시철도 1호선,노포,다대포해수욕장,일반,평일,001-노포+002-범어사+003-남산+004-두실+005-구서+006-장전+007...,001-05:29+002-05:31+003-05:33+004-05:34+005-05...,001-05:29+002-05:31+003-05:33+004-05:35+005-05...,39.6km/h,1544-5005,2023-07-11

## 2. 데이터 처리 및 임베딩

### 2.1 방향 임베딩

In [49]:
# 노선의 방향을 Embedding
df_dVect = df["운행구간기점명"] + df["운행구간종점명"]

# dVect_eigen = list(set((df_dVect).to_list()))
DVECT_EIGEN = util.DVECT_EIGEN_REV

# Check Embedding
dVect_index = [DVECT_EIGEN[direct] for direct in df_dVect]
dVect_index

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 ...]

In [50]:
TARGET_COLUMNS = ["요일구분","열차번호" ,"운행구간정거장","정거장도착시각","정거장출발시각"]
TARGET_COLUMNS_ENG = ["DayType","TrainCode","StationList", "ArriveSchedule","DepartSchedule"]

df_station_schedule = df.loc[:, TARGET_COLUMNS]
df_station_schedule = df_station_schedule.rename(
    columns={idx: new_name for idx, new_name in zip(TARGET_COLUMNS, TARGET_COLUMNS_ENG)}
)

# Insert Direction Vector
df_station_schedule.insert(loc=2,column="DirectionVector",value=pd.Series(dVect_index))

# Save
with open(PATH_STATION_SCHEDULE_REFINE,mode="w",encoding="UTF-8") as f:
    f.write(df_station_schedule.to_json(index=False))
df_station_schedule.head(3)

,DayType,TrainCode,DirectionVector,StationList,ArriveSchedule,DepartSchedule
0,평일,1001,1,001-노포+002-범어사+003-남산+004-두실+005-구서+006-장전+007...,001-05:08+002-05:09+003-05:11+004-05:13+005-05...,001-05:08+002-05:10+003-05:12+004-05:13+005-05...
1,평일,1003,1,001-노포+002-범어사+003-남산+004-두실+005-구서+006-장전+007...,001-05:18+002-05:20+003-05:22+004-05:23+005-05...,001-05:18+002-05:20+003-05:22+004-05:24+005-05...
2,평일,1005,1,001-노포+002-범어사+003-남산+004-두실+005-구서+006-장전+007...,001-05:29+002-05:31+003-05:33+004-05:34+005-05...,001-05:29+002-05:31+003-05:33+004-05:35+005-05...

### 2.2 시간 데이터 처리 및 역명 처리

In [51]:
# 도착시간을 minute으로 mapping 하기위한 함수 정의
def hhmm_to_minute(hhmm: str):
    """
    hhmm_to_minute String Time Format(hh:mm) to Int Minute Time Format for Calculate Difference

    Args:
        hhmm (string): hh:mm format Time String

    Returns:
        int: Minute Time
    """
    HM = hhmm.split(":")
    if "" in HM:
        return np.NaN
    H, M = int(HM[0]), int(HM[1])
    minutes = H * 60 + M if H != 0 else 24 * 60 + M
    return minutes

# trimming 1
trim_target = TARGET_COLUMNS_ENG[2:5]
trimmed_data = [
    df_station_schedule[trim_target].loc[:, trim_target[0]]
    .apply(lambda _x: _x.split("+"))
    .apply(lambda _x: [e.split("-")[-1] for e in _x]),
    df_station_schedule[trim_target].loc[:, trim_target[1]]
    .apply(lambda _x: _x.split("+"))
    .apply(lambda _x: [e.split("-")[-1] for e in _x])
    .apply(lambda _x: [hhmm_to_minute(e) for e in _x]),
    df_station_schedule[trim_target].loc[:, trim_target[2]]
    .apply(lambda _x: _x.split("+"))
    .apply(lambda _x: [e.split("-")[-1] for e in _x])
    .apply(lambda _x: [hhmm_to_minute(e) for e in _x]),
]

# Update to trimmed data
for target_feature, data in zip(trim_target,trimmed_data):
    df_station_schedule[target_feature] = data

# trimming 2 - 노선:INT 추가
df_station_schedule.insert(loc=2,column="LineNumber",value=df["노선명"].apply(lambda _x: _x.split(" ")[-1].replace("호선","")))

#Check
df_station_schedule.head(3)

,DayType,TrainCode,LineNumber,DirectionVector,StationList,ArriveSchedule,DepartSchedule
0,평일,1001,1,1,"[노포, 범어사, 남산, 두실, 구서, 장전, 부산대, 온천장, 명륜, 동래, 교대...","[308, 309, 311, 313, 315, 317, 319, 321, 323, ...","[308, 310, 312, 313, 315, 317, 319, 321, 323, ..."
1,평일,1003,1,1,"[노포, 범어사, 남산, 두실, 구서, 장전, 부산대, 온천장, 명륜, 동래, 교대...","[318, 320, 322, 323, 325, 327, 329, 331, 333, ...","[318, 320, 322, 324, 326, 328, 329, 331, 333, ..."
2,평일,1005,1,1,"[노포, 범어사, 남산, 두실, 구서, 장전, 부산대, 온천장, 명륜, 동래, 교대...","[329, 331, 333, 334, 336, 338, 340, 342, 344, ...","[329, 331, 333, 335, 337, 339, 340, 342, 344, ..."

## 3 요일 별로 데이터 분리하기

In [53]:
# 요일 Embedding
dayType_eigen = list(set((df["요일구분"]).to_list()))
print(dayType_eigen)

# 요일별로 저장
for day in dayType_eigen:
    with open(f"../trimmed_data/stationSchedule{day}.json",mode="w",encoding="UTF-8") as f:
        f.write(df_station_schedule[df["요일구분"] == day].iloc[:,1:].to_json(index=False))
df_station_schedule.head()

['일요일', '토요일', '평일', '공휴일']

,DayType,TrainCode,LineNumber,DirectionVector,StationList,ArriveSchedule,DepartSchedule
0,평일,1001,1,1,"[노포, 범어사, 남산, 두실, 구서, 장전, 부산대, 온천장, 명륜, 동래, 교대...","[308, 309, 311, 313, 315, 317, 319, 321, 323, ...","[308, 310, 312, 313, 315, 317, 319, 321, 323, ..."
1,평일,1003,1,1,"[노포, 범어사, 남산, 두실, 구서, 장전, 부산대, 온천장, 명륜, 동래, 교대...","[318, 320, 322, 323, 325, 327, 329, 331, 333, ...","[318, 320, 322, 324, 326, 328, 329, 331, 333, ..."
2,평일,1005,1,1,"[노포, 범어사, 남산, 두실, 구서, 장전, 부산대, 온천장, 명륜, 동래, 교대...","[329, 331, 333, 334, 336, 338, 340, 342, 344, ...","[329, 331, 333, 335, 337, 339, 340, 342, 344, ..."
3,평일,1007,1,1,"[노포, 범어사, 남산, 두실, 구서, 장전, 부산대, 온천장, 명륜, 동래, 교대...","[340, 342, 344, 345, 347, 349, 351, 353, 355, ...","[340, 342, 344, 346, 348, 350, 351, 353, 355, ..."
4,평일,1009,1,1,"[노포, 범어사, 남산, 두실, 구서, 장전, 부산대, 온천장, 명륜, 동래, 교대...","[351, 353, 355, 356, 358, 360, 362, 364, 366, ...","[351, 353, 355, 357, 359, 361, 362, 364, 366, ..."